spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.0.11:1521:ODBS02
    password: sapiens_hom
    username: sapiens_hom
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
